// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.Birthstones
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("month")]
        public long Month { get; set; }

        [JsonProperty("monthName")]
        public string MonthName { get; set; }

        [JsonProperty("primaryStone")]
        public string PrimaryStone { get; set; }

        [JsonProperty("alternateStones")]
        public string[] AlternateStones { get; set; }

        [JsonProperty("color")]
        public string Color { get; set; }

        [JsonProperty("meaning")]
        public string Meaning { get; set; }

        [JsonProperty("zodiacSigns")]
        public string[] ZodiacSigns { get; set; }

        [JsonProperty("hardness")]
        public double Hardness { get; set; }

        [JsonProperty("mineralFamily")]
        public string MineralFamily { get; set; }

        [JsonProperty("anniversaryYear")]
        public long AnniversaryYear { get; set; }
    }
}
